#include "./ColorChooser.h"
#include "./Crossfade.h"
#include "./DiamondNecklace.h"
#include "./Dimmer.h"
#include "./FuckMyEyes.h"
#include "./Race.h"
#include "./Rainbow.h"
#include "./Stars.h"
#include "./Stripes.h"
// #include "./Strobe.h"